# Default namespace of imported XSD components, used when loaded XSDs do not mention a target namespace
default_namespace: 'http://www.gbif.es/PliC/'
#default_namespace: 'http://www.eol.org/transfer/content/0.3'
#default_namespace: 'http://www.gisin.org/gisin/SpeciesStatus'
#default_namespace: 'eml://ecoinformatics.org/eml-2.1.1'
#default_namespace: 'http://www.tdwg.org/schemas/tcs/1.01'
#default_namespace: 'http://www.tdwg.org/schemas/abcd/2.06'

# Generate RDF terms for XSD components from only these namespaces
namespaces_to_process:
  - 'http://www.gbif.es/PliC/'
#  - 'http://www.eol.org/transfer/content/0.3'
#  - 'http://www.gisin.org/gisin/SpeciesStatus'
#  - 'eml://ecoinformatics.org/eml-2.1.1'
#  - 'http://www.tdwg.org/schemas/tcs/1.01'
#  - 'http://www.tdwg.org/schemas/abcd/2.06'
