# Default namespace of imported XSD components, used when loaded XSDs do not mention a target namespace
default_namespace: 'eml://ecoinformatics.org/eml-2.1.1'

# Generate RDF terms for XSD components from only these namespaces
namespaces_to_process:
  - 'eml://ecoinformatics.org/eml-2.1.1'
