# Default namespace of imported XSD components, used when loaded XSDs do not mention a target namespace
default_namespace: 'http://www.tdwg.org/schemas/tcs/1.01'

# Generate RDF terms for XSD components from only these namespaces
namespaces_to_process:
  - 'http://www.tdwg.org/schemas/tcs/1.01'
